language: go
jobs:
  include:
    - go: 1.13.x
      sudo: true
      services:
        - 'docker'
      script:
        - echo "HELLO WORLD"
        - echo "notasecret=$NOT_SECRET"
        - echo "secret=$SECRET"
        - echo "notasecret=$SH"
        - echo "secret=$DB"
      env:
        - DB=$SECRET
        - SH=$NOT_SECRET
          

after_success:
  - echo "travis go version='$TRAVIS_GO_VERSION'"
