language: go
jobs:
  include:
    - go: 1.13.x
      script:
          - echo "HELLO WORLD"
          - echo "notasecret=$NOT_SECRET"
          - echo "secret=$SECRET"
          

after_success:
  - echo "travis go version='$TRAVIS_GO_VERSION'"
