language: go
jobs:
  include:
    - go: 1.13.x
      script:
          - echo "HELLO WORLD"
          - echo "${NOT_SECRET}"
          - echo "${SECRET}"
          

after_success:
  - echo "travis go version='$TRAVIS_GO_VERSION'"
